apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/UKEODHP/workspace-controller-testenv.git
    targetRevision: HEAD
    path: apps/argocd
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
