apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspaces
  namespace: argocd
spec:
  destination:
    namespace: workspaces
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/UKEODHP/workspace-controller-testenv.git
    targetRevision: HEAD
    path: apps/workspaces
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
